// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"context"
	"github.com/google/wire"
	"weather-server/src/cmd/app"
	"weather-server/src/controllers"
	"weather-server/src/interfaces"
)

// Injectors from container.go:

// Example code for DI Implementation
func CreateContainerInstance(ctx context.Context) (*app.Container, error) {
	controllersServer := controllers.NewServer()
	container := &app.Container{
		Server: controllersServer,
	}
	return container, nil
}

// container.go:

var server = wire.NewSet(controllers.NewServer, wire.Bind(new(interfaces.IServer), new(*controllers.Server)))
