// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ITemperatureCharacterizer is an autogenerated mock type for the ITemperatureCharacterizer type
type ITemperatureCharacterizer struct {
	mock.Mock
}

// CharacterizeTemperature provides a mock function with given fields: temp
func (_m *ITemperatureCharacterizer) CharacterizeTemperature(temp int) string {
	ret := _m.Called(temp)

	if len(ret) == 0 {
		panic("no return value specified for CharacterizeTemperature")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(temp)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewITemperatureCharacterizer creates a new instance of ITemperatureCharacterizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITemperatureCharacterizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITemperatureCharacterizer {
	mock := &ITemperatureCharacterizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
